### ISSUE TITLE
Integrated Gradients target

### ISSUE THREAD

**Issue by Huxwell** [SeldonIO/alibi#627]
I am struggle to understand what target parameter means and how to use it
According to https://docs.seldon.io/projects/alibi/en/latest/methods/IntegratedGradients.html
`target: Defines which element of the model output is considered to compute the gradients.`

My model is a multicategory images regression with last layer
`layers.Dense(3, activation=tf.nn.relu)` , 3 because I have 3 differents regressed scores

When I do
```
import tensorflow as tf
from alibi.explainers import IntegratedGradients


ig  = IntegratedGradients(model_ours,
                          layer=None,
                          method="gausslegendre",
                          n_steps=50,
                          internal_batch_size=100)
ig.explain(X, baselines=None, target=1)
``` 
I will actually get some nicely looking explanations, but they don't seem meaningful. I can change target to 99999999, or -999, or np.array([[1,1,1]]) or in fact np.array([[1,1,1,1,1,1,1,1,1,1]]) to get different explanations, but I don't know what they mean in such case. 
The explanation from your manual seems to be wrong, target doesn't seem to say "which element of the model output is considered to compute the gradient", it rather seems to supply this element's value. However I don't understand dimensionality in such case.

Let's say I make sure I am using the last layer with:

```
print(X.shape,y)
ig  = IntegratedGradients(model_ours,
                          layer = model_ours.layers[-1],
                          method="gausslegendre",
                          n_steps=50,
                          internal_batch_size=100)
ig.explain(X, baselines=None, target=np.array([[5.5,1.0,4.5]])) #this is correct label for this picture
```
Ok, got some explanations, I supplied numbers for 3 outputs, should be fine.
However I can also do, `ig.explain(X, baselines=None, target=np.array([[99]*99]))` and I also get some explanations. I don't understand why didn't the code crash - I just provided a 99 values to 3 neurons, how were they distributed?
Did only first [99,99,99] got feed to the network? Or maybe just the first value [99]?

I have a second question, after I run the code above, I will get:
```
 'predictions': array([[3.5566006, 0.7617401, 3.6028929]], dtype=float32),
  'deltas': array([0.]),
  'target': [array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])]}
  ```
What are 'deltas'? Why only single scalar instead of ie input_width x input_height x channels OR vector of 3 values (because 3 neurons in my dense layer)? Is it the same as loss value (i.e MSE for my model if I used it for training)?  It's usually 0.0, rarely something like 0.4 for me, and I cannot determine what changes it's value.

There is a small secondary issue: [5.5,1.0,4.5] is feed as [5,1,4], which is a minor inconvenience. 

Btw great work with this repo in general, It's great that you maintain it with newer versions of Tensorflow 2.x!  Thanks a lot!
I couldn't get LIME or SHAP running well with new tf and regression at all,

**Comment by gipster** [comment]
Hey @Huxwell . I think it's a bug in the gradient computation with respect to an internal layer. Just to explain: In your case, the target parameter should select the  regression score  for which you want to calculate the gradients. 

You are passing `layer = model_ours.layers[-1]`, which make the code to use the function computing the layer gradients. I had a look at the code and it seems like this function is bugged and it ignores the target. 

I'm investigating. Can you try to run your code without passing any layer and see if it makes sense?

**Comment by gipster** [comment]
Ok, just a quick clarification about the first issue, when you pass `layer=None`: the target is the position of your output respect to which you want to calculate the gradients. In a classification problem, this is the actual prediction, but in case of regression is actually the mere position of your output. In your case is either 0, 1 or 2. You can pass an array like `np.array([0, 1, 1, 2, 0 ...])` of the same size as the number of instances in `X` if you want to specify a different target for each instance. You shouldn't pass something like `np.array([[5.5,1.0,4.5]]))` . 

Actually, I quickly tried to replicate the issue passing some funny targets but I couldn't, the code actually crashes as it should. Can you post a minimal piece of code that replicate this behavior please?

**Comment by Huxwell** [comment]
This is interesting
```
ig.explain(X, baselines=None, target=-123)
```
results in
```
InvalidArgumentError: indices[0] = -123 is not in [0, 400) [Op:GatherV2]
```

**Comment by gipster** [comment]
Hey Huxwell

I think you forgot to do some pooling in your model. If you run 
`model_ours(X).shape`
you get 
`(1, 400, 400, 3)`.

Basically, if you add the dense layers without pooling, your output will be of the same shape as your input.
IG  sees an output with 400 elements, and that's why the code doesn't crash. That's also why it crashes with -123 and returns that error. It will crash also if you pass target =401.  
Does it make sense? can you check to see if your real model also has this problem?

So the code should work fine for 1 dimensional and 2 dimensional outputs (classification and multi regression problems), but I realize that IG doesn't support higher dimensional outputs. 
It all comes down to the function [_select_target](https://github.com/SeldonIO/alibi/blob/ab732a3aa5099f4915762eb2535328fe44de17c1/alibi/explainers/integrated_gradients.py#L98), which only select the correct target if the output is 1-d or 2-d.

**Comment by gipster** [comment]
In any case, I believe the  [_select_target](https://github.com/SeldonIO/alibi/blob/ab732a3aa5099f4915762eb2535328fe44de17c1/alibi/explainers/integrated_gradients.py) function should be fixed. It behave correctly for the most common use cases, but it might have funny behaviours for more unusual ones.

**Comment by Huxwell** [comment]
I've added flatten (in my original model GlobalAvaragePooling2d had similar role), but the code still doesn't crash.
Btw my tf.__version__=2.4.0, and alibi.__version__=0.6.2.
I think I am seeing some non-deterministic behaviour, because I cannot replicate the
`InvalidArgumentError: indices[0] = -123 is not in [0, 400) [Op:GatherV2]` error anymore, even without flatten layer.

```
import os
import numpy as np
import tensorflow as tf
from alibi.explainers import IntegratedGradients
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

model_ours = Sequential([
        layers.Input(shape=(400, 400, 3)),
        layers.Flatten(),
        layers.Dense(64, activation=tf.nn.leaky_relu),
        layers.Dense(3, activation=tf.nn.relu)
    ])

print(model_ours.output_shape)

img = np.random.randint(0,255,[400,400,3])
X = img.reshape([1,400,400,3])

ig  = IntegratedGradients(model_ours,
                          layer=model_ours,
                          method="gausslegendre",
                          n_steps=7,
                          internal_batch_size=2)
ig.explain(X, baselines=None, target=999)
```
Results in


```
(None, 3)
Explanation(meta={
  'name': 'IntegratedGradients',
  'type': ['whitebox'],
  'explanations': ['local'],
  'params': {
              'internal_batch_size': 2,
              'n_steps': 7,
              'method': 'gausslegendre',
              'layer': None}
            ,
  'version': '0.6.2'}
, data={
  'attributions': [array([[0., 0., 0.]], dtype=float32)],
  'X': array([[[[  7, 147, 200],
         [140,  61, 102],
         [ 88,  23, 186],
         ...,
         [ 10,  55,  40],
         [158,  50, 181],
         [ 11,  76,  41]],

        [[231, 161, 167],
         [ 37,  66,  37],
         [114,  40, 221],
         ...,
         [105,  58,  55],
         [241, 159, 229],
         [ 15, 161,  77]]]]),
  'forward_kwargs': {},
  'baselines': array([[[[0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]]),
  'predictions': array([[  0.    , 440.2167,   0.    ]], dtype=float32),
  'deltas': array([0.]),
  'target': [-999]}
)
```

**Comment by gipster** [comment]
Hi Huxwell

I actually copied and pasted your code in a fresh environment and I'm getting the "right error":
```
InvalidArgumentError: indices[0] = -999 is not in [0, 3) [Op:GatherV2]
```
I'm using python 3.8.13, tensorflow 3.8.0 and alibi 0.6.5 (should be all the latest versions). Not sure if this is important, but can you please share which versions did you use to obtain that output?

Also, you are passing a layer: `layer=model_ours`. This is not an actual layer of the model but the model itself, that's why it doesn't show up in the output (layer=None in the output means that IG tried to find the layer `model_ours` in `model_ours.layers` and obviously didn't find it). However, it still interpret it as the last layer, so it will compute the gradients of the last layer (the output) with respect of the same layer (the layer you passed), which is a constant along the path. I think that's the reason you are getting all 0 attributions.

In any case, I have PR almost ready which should eliminate any funny behaviours of the [_select_target](https://github.com/SeldonIO/alibi/blob/61f0c6afd7e5e23585fc3661b4a4aa137db9abb7/alibi/explainers/integrated_gradients.py#L98) . Stay tuned :)

**Comment by gipster** [comment]
Sorry I just saw you shared the version. I also run your code with tf 2.4.0 and alibi 0.6.2 and I still get the error
```
InvalidArgumentError: indices[0] = -999 is not in [0, 3) [Op:GatherV2]
```

**Comment by gipster** [comment]
I don't understand this. There's nothing stochastic in the code. The IG algorithm is completely deterministic.

**Comment by Huxwell** [comment]
pip didn't see 0.6.5 because I was using python 3.6.9
Now I use a conda env with tf==2.8.0, alibi==0.6.5, Python version 3.7.10 
I am working on an ec2 machine with tensorflow pre-installed on multiple conda environments.
Unfortunately the nondeterministic lack of error persists.

I am trying to isolate the conditions for it. I've ruled out: jupyter (no crash when running from console), gpu/cpu (crash or no crash in both versions).

**Comment by jklaise** [comment]
OK that explains the version stuff as Python 3.6 has been unsupported for a while.

Just to clarify, are you saying running a console script is deterministic but Jupyter isn't? Or both are non-deterministic?

Are you reusing the same model? Bear in mind that defining the same model structure is non-deterministic because the weights are initialized randomly. For this you should follow a guide on how to ensure reproducibility with `tensorflow` which itself is notoriously difficult to do, e.g:  https://github.com/NVIDIA/framework-determinism/blob/master/doc/tensorflow.md

**Comment by Huxwell** [comment]
With console I was able to get explanation for target=-999 (this should crash with InvalidArgumentError, but didn't).
With jupyter I sometimes get explanation, sometimes InvalidArgumentError, running the same code (doing restart & clean all output between runs).

**Comment by jklaise** [comment]
Hmm, since we're unable to reproduce it could be helpful if you could share the full environment so we can attempt to replicate it exactly, e.g. a `conda.yaml` would be good to have
